project:
  type: website
  output-dir: _build

metadata-files:
  - api/_sidebar.yml

website:
  title: "pySLAMMER"
  favicon: _static/pySLAMMER_logo_square.svg
  navbar: 
    left:
    - file: index.qmd
      text: Welcome
    - file: quickstart.qmd
      text: Quickstart
    - file: rigid_flex.qmd
      text: Examples
    - file: api/index.qmd
      text: API Reference
    - file: verifications/verification.qmd
      text: Verifications
    title: "pySLAMMER"
    search: true
    tools:
      - icon: github
        href: "https://github.com/lornearnold/pyslammer"

  sidebar:
    - id: asdf
      title: pySLAMMER
      style: "docked"
      search: false
      logo: _static/pySLAMMER_logo_square.svg
      contents: 
        - text: "Overview"
          href: index.qmd
        - text: "Quickstart guide"
          href: quickstart.qmd
        - section: "Examples"
          contents:
            - rigid_flex.qmd
            - batch_simulations.qmd
        - href: reference/index.qmd
        - section: "Verifications"
          href: verification.qmd
          contents:
            - comp_SLAMMER_results.qmd
            - comp_SLAMMER_perf.qmd
            - comp_analytical.qmd


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    default-image-extension: svg

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: pyslammer
  dir: api
  sidebar: api/_sidebar.yml
  sections:
    - title: "API Reference"
      desc: "API reference for pySLAMMER"
      contents:
        - SlidingBlockAnalysis
        - RigidAnalysis
        - Decoupled
        - Coupled