name: Build and Deploy

on:
  push:
    tags:
      - '*docs'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install sphinx
      - name: Build the Sphinx documentation
        run: |
          sphinx-build -b html docs/ build/
      - name: Upload documentation artifact
        if: startsWith(github.ref, 'refs/tags/docs')
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: build/